const express = require('express');
const validate = require('../../middlewares/validate');
const {authValidation} = require('../../validations');
const {authController} = require('../../controllers');
const router = express.Router();
router.post('/login', validate(authValidation.login), authController.loginUser);
router.post('/registration', validate(authValidation.registration), authController.registration);
router.post('/web2/register', validate(authValidation.web2Register), authController.web2Register);
router.post('/web2/login', validate(authValidation.web2Login), authController.web2Login);
router.post('/userVerification',validate(authValidation.userVerification), authController.userVerification);
router.post('/wallet-link/request-nonce', authController.protect, validate(authValidation.requestWalletLinkNonce), authController.requestWalletLinkNonce);
router.post('/wallet-link/confirm', authController.protect, validate(authValidation.confirmWalletLink), authController.confirmWalletLink);
module.exports = router;
